site_url: https://randal.tech
backend:
  name: github
  repo: randalvance/randal-tech
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
  - name: "blogPosts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "blogPosts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}/"
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Cover Image"
        name: "coverImage"
        required: false
        widget: "object"
        collapsed: true
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
            allow_multiple: false
          - label: "Credits"
            name: "credits"
            widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
